#!/bin/bash

source .scripts/server/.environment
echo "VAULT_ADDR = ${VAULT_ADDR}"

SECRET_PATH="/main/topsecret"

echo
echo "put secret"
vault kv put -mount=concourse ${SECRET_PATH} value="{\"secret\": \"carrot is expensive\"}"

echo
echo "get secret from path ${SECRET_PATH}"
vault kv get -mount=concourse -field=value ${SECRET_PATH}


