#!/bin/bash

cd .scripts/server/concourse
pwd

source ../.environment

docker compose up -d

SLEEP=30
echo "Wait for ${SLEEP} seconds, so the server is ready before trying to login to the concourse server"
sleep ${SLEEP}

echo
fly -t tutorial login \
    -c http://localhost:8080 \
    -u test -p test \
    --team-name main

fly targets